// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NB_MVCTest.Data;

#nullable disable

namespace NB_MVCTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250522120716_AddSeedingDataUsers_3")]
    partial class AddSeedingDataUsers_3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NB_MVCTest.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = "30/03/2000",
                            EmailId = "Nandini@gmail.com",
                            FirstName = "Nandini",
                            UserName = "NB123"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = "12/04/2002",
                            EmailId = "Shilpa@gmail.com",
                            FirstName = "Shilpa",
                            UserName = "SH123"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = "28/06/1999",
                            EmailId = "Rahul@gmail.com",
                            FirstName = "Rahul",
                            UserName = "RR123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
